In [ ]:
## using csv files from 
# from https://covidclinicaldata.org/

In [52]:
import pandas as pd
import glob
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [2]:
# using approach from 
# https://stackoverflow.com/questions/20906474/import-multiple-csv-files-into-pandas-and-concatenate-into-one-dataframe

In [48]:
all_files = glob.glob('test_data/05-26_carbonhealth_and_braidhealth.csv')
df = pd.concat((pd.read_csv(f) for f in all_files), sort=False)

In [49]:
pd.set_option('display.max_columns', None)

In [54]:
df.head(10)

,batch_date,test_name,swab_type,covid19_test_results,age,high_risk_exposure_occupation,high_risk_interactions,diabetes,chd,htn,cancer,asthma,copd,autoimmune_dis,smoker,temperature,pulse,sys,dia,rr,sats,rapid_flu_results,rapid_strep_results,ctab,labored_respiration,rhonchi,wheezes,days_since_symptom_onset,cough,cough_severity,fever,sob,sob_severity,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat,cxr_findings,cxr_impression,cxr_label,cxr_link,er_referral
0,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,31,False,NaN,False,False,False,False,False,False,False,False,37.10,63.0,108.0,72.0,17.0,98.0,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
1,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,54,False,True,False,False,True,False,False,False,False,False,36.75,71.0,121.0,74.0,16.0,100.0,NaN,NaN,False,False,False,False,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
2,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,32,False,False,False,False,False,False,False,False,False,False,36.45,62.0,111.0,74.0,16.0,98.0,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
3,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,25,False,False,False,False,False,False,False,False,False,False,36.85,95.0,119.0,75.0,16.0,98.0,NaN,NaN,False,NaN,NaN,False,3.0,True,NaN,True,True,NaN,False,False,True,False,False,False,False,False,NaN,NaN,NaN,NaN,False
4,2020-05-26,"SARS-CoV-2, NAA",Nasopharyngeal,Negative,33,False,False,False,False,False,False,False,False,False,False,36.75,70.0,122.0,82.0,12.0,100.0,NaN,NaN,False,False,False,False,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
5,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,45,False,True,False,False,True,False,False,False,False,False,36.90,73.0,151.0,93.0,16.0,99.0,NaN,NaN,False,False,False,False,5.0,True,Moderate,False,False,NaN,False,True,True,False,False,False,True,False,NaN,NaN,NaN,NaN,False
6,2020-05-26,"SARS-CoV-2, NAA",Nasal,Negative,58,False,False,True,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
7,2020-05-26,"SARS-CoV-2, NAA",Nasal,Negative,45,False,True,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
8,2020-05-26,"SARS-CoV-2, NAA",Nasal,Negative,46,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
9,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,23,False,False,False,False,False,False,False,False,False,True,36.30,72.0,138.0,80.0,12.0,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False,True,NaN,False,True,True,False,False,False,False,True,NaN,NaN,NaN,NaN,False

In [55]:
df.columns

Index(['batch_date', 'test_name', 'swab_type', 'covid19_test_results', 'age',
       'high_risk_exposure_occupation', 'high_risk_interactions', 'diabetes',
       'chd', 'htn', 'cancer', 'asthma', 'copd', 'autoimmune_dis', 'smoker',
       'temperature', 'pulse', 'sys', 'dia', 'rr', 'sats', 'rapid_flu_results',
       'rapid_strep_results', 'ctab', 'labored_respiration', 'rhonchi',
       'wheezes', 'days_since_symptom_onset', 'cough', 'cough_severity',
       'fever', 'sob', 'sob_severity', 'diarrhea', 'fatigue', 'headache',
       'loss_of_smell', 'loss_of_taste', 'runny_nose', 'muscle_sore',
       'sore_throat', 'cxr_findings', 'cxr_impression', 'cxr_label',
       'cxr_link', 'er_referral'],
      dtype='object')

In [56]:
# get the symptoms

In [74]:
df_symptoms = pysqldf("""
SELECT
    covid19_test_results, labored_respiration, rhonchi,
    wheezes, cough, cough_severity,
    fever, sob, sob_severity, diarrhea, fatigue, headache,
    loss_of_smell, loss_of_taste, runny_nose, muscle_sore,
    sore_throat
FROM
    df
""")

In [76]:
df_symptoms.describe()

,labored_respiration,rhonchi,wheezes,cough,fever,sob,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat
count,428.000000,295.000000,314.000000,746.000000,522.000000,741.000000,741.000000,741.000000,741.000000,741.000000,741.000000,741.000000,741.000000,741.000000
mean,0.002336,0.138983,0.178344,0.092493,0.047893,0.036437,0.020243,0.059379,0.071525,0.014845,0.006748,0.053981,0.051282,0.059379
std,0.048337,0.346517,0.383413,0.289915,0.213744,0.187502,0.140925,0.236493,0.257874,0.121013,0.081922,0.226133,0.220721,0.236493
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [77]:
df.head()

,batch_date,test_name,swab_type,covid19_test_results,age,high_risk_exposure_occupation,high_risk_interactions,diabetes,chd,htn,cancer,asthma,copd,autoimmune_dis,smoker,temperature,pulse,sys,dia,rr,sats,rapid_flu_results,rapid_strep_results,ctab,labored_respiration,rhonchi,wheezes,days_since_symptom_onset,cough,cough_severity,fever,sob,sob_severity,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat,cxr_findings,cxr_impression,cxr_label,cxr_link,er_referral
0,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,31,False,NaN,False,False,False,False,False,False,False,False,37.10,63.0,108.0,72.0,17.0,98.0,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
1,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,54,False,True,False,False,True,False,False,False,False,False,36.75,71.0,121.0,74.0,16.0,100.0,NaN,NaN,False,False,False,False,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
2,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,32,False,False,False,False,False,False,False,False,False,False,36.45,62.0,111.0,74.0,16.0,98.0,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False
3,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,25,False,False,False,False,False,False,False,False,False,False,36.85,95.0,119.0,75.0,16.0,98.0,NaN,NaN,False,NaN,NaN,False,3.0,True,NaN,True,True,NaN,False,False,True,False,False,False,False,False,NaN,NaN,NaN,NaN,False
4,2020-05-26,"SARS-CoV-2, NAA",Nasopharyngeal,Negative,33,False,False,False,False,False,False,False,False,False,False,36.75,70.0,122.0,82.0,12.0,100.0,NaN,NaN,False,False,False,False,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,False

In [79]:
# run a simple query
sql = """
SELECT
    *
FROM
    df
WHERE
    fatigue = 1
"""

r = pysqldf(sql)

In [80]:
r.head()

,batch_date,test_name,swab_type,covid19_test_results,age,high_risk_exposure_occupation,high_risk_interactions,diabetes,chd,htn,cancer,asthma,copd,autoimmune_dis,smoker,temperature,pulse,sys,dia,rr,sats,rapid_flu_results,rapid_strep_results,ctab,labored_respiration,rhonchi,wheezes,days_since_symptom_onset,cough,cough_severity,fever,sob,sob_severity,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat,cxr_findings,cxr_impression,cxr_label,cxr_link,er_referral
0,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,45,0,1.0,0,0,1,0,0,0,0,0,36.90,73.0,151.0,93.0,16.0,99.0,None,None,0.0,0.0,0.0,0.0,5.0,1,Moderate,0.0,0,None,0,1,1,0,0,0,1,0,None,None,None,None,0
1,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,23,0,0.0,0,0,0,0,0,0,0,1,36.30,72.0,138.0,80.0,12.0,98.0,None,None,NaN,NaN,NaN,NaN,NaN,1,None,0.0,1,None,0,1,1,0,0,0,0,1,None,None,None,None,0
2,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,23,1,1.0,0,0,0,0,1,0,0,1,36.75,65.0,115.0,76.0,12.0,100.0,None,None,0.0,0.0,1.0,1.0,21.0,1,Mild,0.0,1,Moderate,0,1,1,0,0,1,0,1,None,None,None,None,0
3,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Positive,34,0,0.0,0,0,0,0,0,0,0,0,37.60,96.0,103.0,71.0,12.0,98.0,None,None,NaN,NaN,NaN,NaN,3.0,1,None,NaN,0,None,0,1,0,0,0,0,1,0,None,None,None,None,0
4,2020-05-26,SARS COV2 NAAT,Nasopharyngeal,Negative,31,0,0.0,0,0,0,0,0,0,0,0,37.00,74.0,137.0,84.0,16.0,100.0,None,None,0.0,0.0,0.0,0.0,4.0,1,Mild,NaN,1,Mild,1,1,1,0,0,1,1,1,None,None,None,None,0

In [81]:
r.describe()

,age,high_risk_exposure_occupation,high_risk_interactions,diabetes,chd,htn,cancer,asthma,copd,autoimmune_dis,smoker,temperature,pulse,sys,dia,rr,sats,ctab,labored_respiration,rhonchi,wheezes,days_since_symptom_onset,cough,fever,sob,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat,er_referral
count,44.000000,44.000000,41.000000,44.0,44.0,44.000000,44.0,44.000000,44.0,44.0,44.000000,38.000000,40.000000,37.000000,37.000000,35.000000,36.000000,35.000000,37.0,32.000000,32.000000,41.000000,44.000000,36.000000,44.000000,44.000000,44.0,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.0
mean,32.363636,0.181818,0.292683,0.0,0.0,0.090909,0.0,0.068182,0.0,0.0,0.136364,37.036842,79.975000,123.567568,79.810811,15.028571,98.111111,0.028571,0.0,0.062500,0.062500,7.585366,0.500000,0.416667,0.295455,0.204545,1.0,0.659091,0.113636,0.090909,0.363636,0.568182,0.409091,0.0
std,11.297439,0.390154,0.460646,0.0,0.0,0.290803,0.0,0.254972,0.0,0.0,0.347142,0.410287,14.605035,16.543781,11.510473,2.843835,1.409717,0.169031,0.0,0.245935,0.245935,14.432560,0.505781,0.500000,0.461522,0.408032,0.0,0.479495,0.321038,0.290803,0.486607,0.501056,0.497350,0.0
min,8.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,36.300000,56.000000,94.000000,49.000000,12.000000,95.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,24.750000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,36.750000,68.500000,109.000000,71.000000,12.000000,97.000000,0.000000,0.0,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
50%,29.500000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,36.925000,78.500000,124.000000,80.000000,16.000000,98.000000,0.000000,0.0,0.000000,0.000000,4.000000,0.500000,0.000000,0.000000,0.000000,1.0,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0
75%,39.250000,0.000000,1.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,37.237500,88.750000,138.000000,88.000000,16.000000,99.000000,0.000000,0.0,0.000000,0.000000,5.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.0
max,64.000000,1.000000,1.000000,0.0,0.0,1.000000,0.0,1.000000,0.0,0.0,1.000000,38.400000,114.000000,156.000000,104.000000,24.000000,100.000000,1.000000,0.0,1.000000,1.000000,90.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [82]:
# a group by query

In [84]:
pysqldf("""
SELECT 
    covid19_test_results, fatigue, COUNT(covid19_test_results, fatigue)
FROM
    df_symptoms
GROUP BY 
    covid19_test_results, fatigue
""")

PandaSQLException: (sqlite3.OperationalError) wrong number of arguments to function COUNT()
[SQL:
SELECT
    covid19_test_results, fatigue, COUNT(covid19_test_results, fatigue)
FROM
    df_symptoms
GROUP BY
    covid19_test_results, fatigue
]
(Background on this error at: https://sqlalche.me/e/14/e3q8)